[package]
name = "graphical-sort"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
rand = "0.8.5"


[dependencies.glfw]
version = "0.53.0"
# features = ["wayland"]
